# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on: workflow_dispatch
  

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Setup Xcode version
      with:
        xcode-version: '26.0'
      uses: maxim-lobanov/setup-xcode@v1.6.0
    - name: MAUI iOS workload install
      run: dotnet workload install maui-ios
    - name: Restore dependencies
      run: dotnet restore -p:TargetFramework=net9.0-ios
    - name: Build
      run: dotnet publish OpenUtauMobile/OpenUtauMobile.csproj \-f net9.0-ios \-c Debug \-p:ArchiveOnBuild=true \-p:RuntimeIdentifier=ios-arm64 \-p:TargetFrameworks=net9.0-ios
    - name: Artifact
      uses: actions/download-artifact@v7.0.0
      with:
        name: OpenUtauMobile.ipa
